services:
  app:
    container_name: cpp_api_container
    build:
      context: .
      dockerfile: docker/app_build/Dockerfile
    working_dir: /work
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - cpp_api
    volumes:
      - ./media:/work/media

  nginx:
    image: nginx:1.27-alpine
    container_name: cpp_api_nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.test.conf:ro
      - ./media:/work/media:ro
    depends_on:
      - app
    networks:
      - cpp_api

  redis:
    image: redis:alpine
    container_name: cpp_api_redis_container
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" ping | grep -q PONG"]
      interval: 5s
      timeout: 2s
      retries: 10
    env_file:
      - .env.test
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - cpp_api

  db:
    container_name: cpp_api_db_container
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data  
    networks:
      - cpp_api

  migrate:
    image: migrate/migrate:4
    profiles: ["dev"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro
    env_file:
      - .env
    entrypoint: ["migrate", "-path", "/migrations", "-database", "${DATABASE_MIGRATION_URL}"]
    networks: [cpp_api]

volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  cpp_api:
    driver: bridge
